# Generated by Django 2.2 on 2020-09-18 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontuacao',
            old_name='usuario',
            new_name='user',
        ),
    ]
